force_keyboard_focus = true                                                 # forces keyboard forcus to stay in Walker
selection_wrap = true                                                       # wrap list if at bottom or top
theme = "omarchy-default"                                                   # theme to use
additional_theme_location = "~/.local/share/omarchy/default/walker/themes/"
hide_action_hints = true                                                    # globally hide the action hints

[placeholders]
"default" = { input = "ï€‚ Search...", list = "No Results" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"

[keybinds]
quick_activate = []

[columns]
symbols = 1 # providers to be queried by default

[providers]
max_results = 256 # 256 should be enough for everyone
default = [
  "desktopapplications",
  "websearch",
]

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[[providers.prefixes]]
prefix = "."
provider = "files"

[[providers.prefixes]]
prefix = ":"
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

<<<<<<< HEAD
<<<<<<< HEAD
[[builtins.websearch.entries]]
name = "Google"
url = "https://www.google.com/search?q=%TERM%"

[[builtins.websearch.entries]]
name = "DuckDuckGo"
url = "https://duckduckgo.com/?q=%TERM%"
switcher_only = true

[[builtins.websearch.entries]]
name = "Ecosia"
url = "https://www.ecosia.org/search?q=%TERM%"
switcher_only = true

[builtins.dmenu]
hidden = true
weight = 5
name = "dmenu"
placeholder = "Dmenu"
switcher_only = true
show_icon_when_single = true

=======
>>>>>>> upstream/master
[builtins.translation]
hidden = true
=======
[[providers.prefixes]]
prefix = "$"
provider = "clipboard"
<<<<<<< HEAD
>>>>>>> upstream/master
=======

[[emergencies]]
text = "Restart Walker"
command = "omarchy-restart-walker"
>>>>>>> upstream/master
